---
- hosts: ec2_tpp_prod
  gather_facts: true
  tasks:
    - name: Setting up Prod servers
      debug:
        msg: "Prod server setup complete."
    
    - name: Stop existing Docker container
      docker_container:
        name: "tpp-app"
        state: absent
      ignore_errors: yes
      become: yes

    - name: Remove Docker image if exists
      docker_image:
        name: "dengol/tpp-app"
        state: absent
        force_absent: true
      ignore_errors: yes
      become: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: dengol/tpp-app:latest
        source: pull
      become: yes

    - name: Run the Docker container
      community.docker.docker_container:
        name: tpp-app
        image: dengol/tpp-app
        state: started
        restart_policy: always
        ports:
          - "8081:8081"  # Map container's port 8080 to host's port 8080
      become: yes
